# -*- coding: utf-8 -*-
"""static.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mGsdl7CpQXPzdzGMSR53Ott_FqbbSnf4
"""

# 掛載雲端硬碟
from google.colab import drive
drive.mount('/content/drive')

import requests
from bs4 import BeautifulSoup
import csv

url = "https://www.books.com.tw/web/sys_saletopb/books/02/"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, "html.parser")

statics = soup.select("li.item")
static_data = []

for static in statics:
    name_tag = static.select_one("h4 a")
    author_tag = static.select_one(".msg a")

    # ✅ 處理價格：抓第二個 <b>
    price_bs = static.select("li.price_a b")
    if len(price_bs) >= 2:
        price = price_bs[1].text.strip()
    else:
        price = ""

    name = name_tag.text.strip() if name_tag else ""
    author = author_tag.text.strip() if author_tag else ""

    # 過濾全部都沒資料的項目
    if not name and not author and not price:
        continue

    static_data.append([
        name or "無資料",
        author or "無資料",
        price or "無價格"
    ])

# 儲存 CSV
with open("static.csv", "w", newline="", encoding="utf-8-sig") as f:
    writer = csv.writer(f)
    writer.writerow(["書名", "作者", "價格"])
    writer.writerows(static_data)

# 複製到雲端硬碟
import shutil
shutil.copy("static.csv", "/content/drive/MyDrive/開放平台/static.csv")